/* Please note that this file is generated by the VulkanSharp's generator. Do not edit directly.

   Licensed under the MIT license.

   Copyright 2016 Xamarin Inc

   This notice may not be removed from any source distribution.
   See LICENSE file for licensing details.
*/

using System;

namespace Vulkan.Interop
{
	internal partial struct PhysicalDeviceProperties
	{
		internal UInt32 ApiVersion;
		internal UInt32 DriverVersion;
		internal UInt32 VendorId;
		internal UInt32 DeviceId;
		internal PhysicalDeviceType DeviceType;
		internal unsafe fixed byte DeviceName[256];
		internal unsafe fixed byte PipelineCacheUuid[16];
		internal PhysicalDeviceLimits Limits;
		internal PhysicalDeviceSparseProperties SparseProperties;
	}

	internal partial struct ExtensionProperties
	{
		internal unsafe fixed byte ExtensionName[256];
		internal UInt32 SpecVersion;
	}

	internal partial struct LayerProperties
	{
		internal unsafe fixed byte LayerName[256];
		internal UInt32 SpecVersion;
		internal UInt32 ImplementationVersion;
		internal unsafe fixed byte Description[256];
	}

	internal partial struct ApplicationInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal IntPtr ApplicationName;
		internal UInt32 ApplicationVersion;
		internal IntPtr EngineName;
		internal UInt32 EngineVersion;
		internal UInt32 ApiVersion;
	}

	internal partial struct AllocationCallbacks
	{
		internal IntPtr UserData;
		internal IntPtr PfnAllocation;
		internal IntPtr PfnReallocation;
		internal IntPtr PfnFree;
		internal IntPtr PfnInternalAllocation;
		internal IntPtr PfnInternalFree;
	}

	internal partial struct DeviceQueueCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal UInt32 QueueFamilyIndex;
		internal UInt32 QueueCount;
		internal IntPtr QueuePriorities;
	}

	internal partial struct DeviceCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal UInt32 QueueCreateInfoCount;
		internal IntPtr QueueCreateInfos;
		internal UInt32 EnabledLayerCount;
		internal IntPtr EnabledLayerNames;
		internal UInt32 EnabledExtensionCount;
		internal IntPtr EnabledExtensionNames;
		internal IntPtr EnabledFeatures;
	}

	internal partial struct InstanceCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal IntPtr ApplicationInfo;
		internal UInt32 EnabledLayerCount;
		internal IntPtr EnabledLayerNames;
		internal UInt32 EnabledExtensionCount;
		internal IntPtr EnabledExtensionNames;
	}

	internal partial struct PhysicalDeviceMemoryProperties
	{
		internal UInt32 MemoryTypeCount;
		internal MemoryType MemoryTypes0;
		internal MemoryType MemoryTypes1;
		internal MemoryType MemoryTypes2;
		internal MemoryType MemoryTypes3;
		internal MemoryType MemoryTypes4;
		internal MemoryType MemoryTypes5;
		internal MemoryType MemoryTypes6;
		internal MemoryType MemoryTypes7;
		internal MemoryType MemoryTypes8;
		internal MemoryType MemoryTypes9;
		internal MemoryType MemoryTypes10;
		internal MemoryType MemoryTypes11;
		internal MemoryType MemoryTypes12;
		internal MemoryType MemoryTypes13;
		internal MemoryType MemoryTypes14;
		internal MemoryType MemoryTypes15;
		internal MemoryType MemoryTypes16;
		internal MemoryType MemoryTypes17;
		internal MemoryType MemoryTypes18;
		internal MemoryType MemoryTypes19;
		internal MemoryType MemoryTypes20;
		internal MemoryType MemoryTypes21;
		internal MemoryType MemoryTypes22;
		internal MemoryType MemoryTypes23;
		internal MemoryType MemoryTypes24;
		internal MemoryType MemoryTypes25;
		internal MemoryType MemoryTypes26;
		internal MemoryType MemoryTypes27;
		internal MemoryType MemoryTypes28;
		internal MemoryType MemoryTypes29;
		internal MemoryType MemoryTypes30;
		internal MemoryType MemoryTypes31;
		internal UInt32 MemoryHeapCount;
		internal MemoryHeap MemoryHeaps0;
		internal MemoryHeap MemoryHeaps1;
		internal MemoryHeap MemoryHeaps2;
		internal MemoryHeap MemoryHeaps3;
		internal MemoryHeap MemoryHeaps4;
		internal MemoryHeap MemoryHeaps5;
		internal MemoryHeap MemoryHeaps6;
		internal MemoryHeap MemoryHeaps7;
		internal MemoryHeap MemoryHeaps8;
		internal MemoryHeap MemoryHeaps9;
		internal MemoryHeap MemoryHeaps10;
		internal MemoryHeap MemoryHeaps11;
		internal MemoryHeap MemoryHeaps12;
		internal MemoryHeap MemoryHeaps13;
		internal MemoryHeap MemoryHeaps14;
		internal MemoryHeap MemoryHeaps15;
	}

	internal partial struct MemoryAllocateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal DeviceSize AllocationSize;
		internal UInt32 MemoryTypeIndex;
	}

	internal partial struct MappedMemoryRange
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 Memory;
		internal DeviceSize Offset;
		internal DeviceSize Size;
	}

	internal partial struct DescriptorBufferInfo
	{
		internal UInt64 Buffer;
		internal DeviceSize Offset;
		internal DeviceSize Range;
	}

	internal partial struct DescriptorImageInfo
	{
		internal UInt64 Sampler;
		internal UInt64 ImageView;
		internal ImageLayout ImageLayout;
	}

	internal partial struct WriteDescriptorSet
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 DstSet;
		internal UInt32 DstBinding;
		internal UInt32 DstArrayElement;
		internal UInt32 DescriptorCount;
		internal DescriptorType DescriptorType;
		internal IntPtr ImageInfo;
		internal IntPtr BufferInfo;
		internal IntPtr TexelBufferView;
	}

	internal partial struct CopyDescriptorSet
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 SrcSet;
		internal UInt32 SrcBinding;
		internal UInt32 SrcArrayElement;
		internal UInt64 DstSet;
		internal UInt32 DstBinding;
		internal UInt32 DstArrayElement;
		internal UInt32 DescriptorCount;
	}

	internal partial struct BufferCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal BufferCreateFlags Flags;
		internal DeviceSize Size;
		internal BufferUsageFlags Usage;
		internal SharingMode SharingMode;
		internal UInt32 QueueFamilyIndexCount;
		internal IntPtr QueueFamilyIndices;
	}

	internal partial struct BufferViewCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal UInt64 Buffer;
		internal Format Format;
		internal DeviceSize Offset;
		internal DeviceSize Range;
	}

	internal partial struct MemoryBarrier
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal AccessFlags SrcAccessMask;
		internal AccessFlags DstAccessMask;
	}

	internal partial struct BufferMemoryBarrier
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal AccessFlags SrcAccessMask;
		internal AccessFlags DstAccessMask;
		internal UInt32 SrcQueueFamilyIndex;
		internal UInt32 DstQueueFamilyIndex;
		internal UInt64 Buffer;
		internal DeviceSize Offset;
		internal DeviceSize Size;
	}

	internal partial struct ImageMemoryBarrier
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal AccessFlags SrcAccessMask;
		internal AccessFlags DstAccessMask;
		internal ImageLayout OldLayout;
		internal ImageLayout NewLayout;
		internal UInt32 SrcQueueFamilyIndex;
		internal UInt32 DstQueueFamilyIndex;
		internal UInt64 Image;
		internal ImageSubresourceRange SubresourceRange;
	}

	internal partial struct ImageCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal ImageCreateFlags Flags;
		internal ImageType ImageType;
		internal Format Format;
		internal Extent3D Extent;
		internal UInt32 MipLevels;
		internal UInt32 ArrayLayers;
		internal SampleCountFlags Samples;
		internal ImageTiling Tiling;
		internal ImageUsageFlags Usage;
		internal SharingMode SharingMode;
		internal UInt32 QueueFamilyIndexCount;
		internal IntPtr QueueFamilyIndices;
		internal ImageLayout InitialLayout;
	}

	internal partial struct ImageViewCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal UInt64 Image;
		internal ImageViewType ViewType;
		internal Format Format;
		internal ComponentMapping Components;
		internal ImageSubresourceRange SubresourceRange;
	}

	internal partial struct SparseMemoryBind
	{
		internal DeviceSize ResourceOffset;
		internal DeviceSize Size;
		internal UInt64 Memory;
		internal DeviceSize MemoryOffset;
		internal SparseMemoryBindFlags Flags;
	}

	internal partial struct SparseImageMemoryBind
	{
		internal ImageSubresource Subresource;
		internal Offset3D Offset;
		internal Extent3D Extent;
		internal UInt64 Memory;
		internal DeviceSize MemoryOffset;
		internal SparseMemoryBindFlags Flags;
	}

	internal partial struct SparseBufferMemoryBindInfo
	{
		internal UInt64 Buffer;
		internal UInt32 BindCount;
		internal IntPtr Binds;
	}

	internal partial struct SparseImageOpaqueMemoryBindInfo
	{
		internal UInt64 Image;
		internal UInt32 BindCount;
		internal IntPtr Binds;
	}

	internal partial struct SparseImageMemoryBindInfo
	{
		internal UInt64 Image;
		internal UInt32 BindCount;
		internal IntPtr Binds;
	}

	internal partial struct BindSparseInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 WaitSemaphoreCount;
		internal IntPtr WaitSemaphores;
		internal UInt32 BufferBindCount;
		internal IntPtr BufferBinds;
		internal UInt32 ImageOpaqueBindCount;
		internal IntPtr ImageOpaqueBinds;
		internal UInt32 ImageBindCount;
		internal IntPtr ImageBinds;
		internal UInt32 SignalSemaphoreCount;
		internal IntPtr SignalSemaphores;
	}

	internal partial struct ImageBlit
	{
		internal ImageSubresourceLayers SrcSubresource;
		internal Offset3D SrcOffsets0;
		internal Offset3D SrcOffsets1;
		internal ImageSubresourceLayers DstSubresource;
		internal Offset3D DstOffsets0;
		internal Offset3D DstOffsets1;
	}

	internal partial struct ShaderModuleCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal UIntPtr CodeSize;
		internal IntPtr Code;
	}

	internal partial struct DescriptorSetLayoutBinding
	{
		internal UInt32 Binding;
		internal DescriptorType DescriptorType;
		internal UInt32 DescriptorCount;
		internal ShaderStageFlags StageFlags;
		internal IntPtr ImmutableSamplers;
	}

	internal partial struct DescriptorSetLayoutCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal DescriptorSetLayoutCreateFlags Flags;
		internal UInt32 BindingCount;
		internal IntPtr Bindings;
	}

	internal partial struct DescriptorPoolCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal DescriptorPoolCreateFlags Flags;
		internal UInt32 MaxSets;
		internal UInt32 PoolSizeCount;
		internal IntPtr PoolSizes;
	}

	internal partial struct DescriptorSetAllocateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 DescriptorPool;
		internal UInt32 DescriptorSetCount;
		internal IntPtr SetLayouts;
	}

	internal partial struct SpecializationInfo
	{
		internal UInt32 MapEntryCount;
		internal IntPtr MapEntries;
		internal UIntPtr DataSize;
		internal IntPtr Data;
	}

	internal partial struct PipelineShaderStageCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal ShaderStageFlags Stage;
		internal UInt64 Module;
		internal IntPtr Name;
		internal IntPtr SpecializationInfo;
	}

	internal partial struct ComputePipelineCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal PipelineCreateFlags Flags;
		internal PipelineShaderStageCreateInfo Stage;
		internal UInt64 Layout;
		internal UInt64 BasePipelineHandle;
		internal Int32 BasePipelineIndex;
	}

	internal partial struct PipelineVertexInputStateCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal UInt32 VertexBindingDescriptionCount;
		internal IntPtr VertexBindingDescriptions;
		internal UInt32 VertexAttributeDescriptionCount;
		internal IntPtr VertexAttributeDescriptions;
	}

	internal partial struct PipelineInputAssemblyStateCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal PrimitiveTopology Topology;
		internal Bool32 PrimitiveRestartEnable;
	}

	internal partial struct PipelineTessellationStateCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal UInt32 PatchControlPoints;
	}

	internal partial struct PipelineViewportStateCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal UInt32 ViewportCount;
		internal IntPtr Viewports;
		internal UInt32 ScissorCount;
		internal IntPtr Scissors;
	}

	internal partial struct PipelineRasterizationStateCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal Bool32 DepthClampEnable;
		internal Bool32 RasterizerDiscardEnable;
		internal PolygonMode PolygonMode;
		internal CullModeFlags CullMode;
		internal FrontFace FrontFace;
		internal Bool32 DepthBiasEnable;
		internal float DepthBiasConstantFactor;
		internal float DepthBiasClamp;
		internal float DepthBiasSlopeFactor;
		internal float LineWidth;
	}

	internal partial struct PipelineMultisampleStateCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal SampleCountFlags RasterizationSamples;
		internal Bool32 SampleShadingEnable;
		internal float MinSampleShading;
		internal IntPtr SampleMask;
		internal Bool32 AlphaToCoverageEnable;
		internal Bool32 AlphaToOneEnable;
	}

	internal partial struct PipelineColorBlendStateCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal Bool32 LogicOpEnable;
		internal LogicOp LogicOp;
		internal UInt32 AttachmentCount;
		internal IntPtr Attachments;
		internal unsafe fixed float BlendConstants[4];
	}

	internal partial struct PipelineDynamicStateCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal UInt32 DynamicStateCount;
		internal IntPtr DynamicStates;
	}

	internal partial struct PipelineDepthStencilStateCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal Bool32 DepthTestEnable;
		internal Bool32 DepthWriteEnable;
		internal CompareOp DepthCompareOp;
		internal Bool32 DepthBoundsTestEnable;
		internal Bool32 StencilTestEnable;
		internal StencilOpState Front;
		internal StencilOpState Back;
		internal float MinDepthBounds;
		internal float MaxDepthBounds;
	}

	internal partial struct GraphicsPipelineCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal PipelineCreateFlags Flags;
		internal UInt32 StageCount;
		internal IntPtr Stages;
		internal IntPtr VertexInputState;
		internal IntPtr InputAssemblyState;
		internal IntPtr TessellationState;
		internal IntPtr ViewportState;
		internal IntPtr RasterizationState;
		internal IntPtr MultisampleState;
		internal IntPtr DepthStencilState;
		internal IntPtr ColorBlendState;
		internal IntPtr DynamicState;
		internal UInt64 Layout;
		internal UInt64 RenderPass;
		internal UInt32 Subpass;
		internal UInt64 BasePipelineHandle;
		internal Int32 BasePipelineIndex;
	}

	internal partial struct PipelineCacheCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal UIntPtr InitialDataSize;
		internal IntPtr InitialData;
	}

	internal partial struct PipelineLayoutCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal UInt32 SetLayoutCount;
		internal IntPtr SetLayouts;
		internal UInt32 PushConstantRangeCount;
		internal IntPtr PushConstantRanges;
	}

	internal partial struct SamplerCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal Filter MagFilter;
		internal Filter MinFilter;
		internal SamplerMipmapMode MipmapMode;
		internal SamplerAddressMode AddressModeU;
		internal SamplerAddressMode AddressModeV;
		internal SamplerAddressMode AddressModeW;
		internal float MipLodBias;
		internal Bool32 AnisotropyEnable;
		internal float MaxAnisotropy;
		internal Bool32 CompareEnable;
		internal CompareOp CompareOp;
		internal float MinLod;
		internal float MaxLod;
		internal BorderColor BorderColor;
		internal Bool32 UnnormalizedCoordinates;
	}

	internal partial struct CommandPoolCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal CommandPoolCreateFlags Flags;
		internal UInt32 QueueFamilyIndex;
	}

	internal partial struct CommandBufferAllocateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 CommandPool;
		internal CommandBufferLevel Level;
		internal UInt32 CommandBufferCount;
	}

	internal partial struct CommandBufferInheritanceInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 RenderPass;
		internal UInt32 Subpass;
		internal UInt64 Framebuffer;
		internal Bool32 OcclusionQueryEnable;
		internal QueryControlFlags QueryFlags;
		internal QueryPipelineStatisticFlags PipelineStatistics;
	}

	internal partial struct CommandBufferBeginInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal CommandBufferUsageFlags Flags;
		internal IntPtr InheritanceInfo;
	}

	internal partial struct RenderPassBeginInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 RenderPass;
		internal UInt64 Framebuffer;
		internal Rect2D RenderArea;
		internal UInt32 ClearValueCount;
		internal IntPtr ClearValues;
	}

	internal partial struct ClearAttachment
	{
		internal ImageAspectFlags AspectMask;
		internal UInt32 ColorAttachment;
		internal ClearValue ClearValue;
	}

	internal partial struct SubpassDescription
	{
		internal SubpassDescriptionFlags Flags;
		internal PipelineBindPoint PipelineBindPoint;
		internal UInt32 InputAttachmentCount;
		internal IntPtr InputAttachments;
		internal UInt32 ColorAttachmentCount;
		internal IntPtr ColorAttachments;
		internal IntPtr ResolveAttachments;
		internal IntPtr DepthStencilAttachment;
		internal UInt32 PreserveAttachmentCount;
		internal IntPtr PreserveAttachments;
	}

	internal partial struct RenderPassCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal UInt32 AttachmentCount;
		internal IntPtr Attachments;
		internal UInt32 SubpassCount;
		internal IntPtr Subpasses;
		internal UInt32 DependencyCount;
		internal IntPtr Dependencies;
	}

	internal partial struct EventCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
	}

	internal partial struct FenceCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal FenceCreateFlags Flags;
	}

	internal partial struct PhysicalDeviceLimits
	{
		internal UInt32 MaxImageDimension1D;
		internal UInt32 MaxImageDimension2D;
		internal UInt32 MaxImageDimension3D;
		internal UInt32 MaxImageDimensionCube;
		internal UInt32 MaxImageArrayLayers;
		internal UInt32 MaxTexelBufferElements;
		internal UInt32 MaxUniformBufferRange;
		internal UInt32 MaxStorageBufferRange;
		internal UInt32 MaxPushConstantsSize;
		internal UInt32 MaxMemoryAllocationCount;
		internal UInt32 MaxSamplerAllocationCount;
		internal DeviceSize BufferImageGranularity;
		internal DeviceSize SparseAddressSpaceSize;
		internal UInt32 MaxBoundDescriptorSets;
		internal UInt32 MaxPerStageDescriptorSamplers;
		internal UInt32 MaxPerStageDescriptorUniformBuffers;
		internal UInt32 MaxPerStageDescriptorStorageBuffers;
		internal UInt32 MaxPerStageDescriptorSampledImages;
		internal UInt32 MaxPerStageDescriptorStorageImages;
		internal UInt32 MaxPerStageDescriptorInputAttachments;
		internal UInt32 MaxPerStageResources;
		internal UInt32 MaxDescriptorSetSamplers;
		internal UInt32 MaxDescriptorSetUniformBuffers;
		internal UInt32 MaxDescriptorSetUniformBuffersDynamic;
		internal UInt32 MaxDescriptorSetStorageBuffers;
		internal UInt32 MaxDescriptorSetStorageBuffersDynamic;
		internal UInt32 MaxDescriptorSetSampledImages;
		internal UInt32 MaxDescriptorSetStorageImages;
		internal UInt32 MaxDescriptorSetInputAttachments;
		internal UInt32 MaxVertexInputAttributes;
		internal UInt32 MaxVertexInputBindings;
		internal UInt32 MaxVertexInputAttributeOffset;
		internal UInt32 MaxVertexInputBindingStride;
		internal UInt32 MaxVertexOutputComponents;
		internal UInt32 MaxTessellationGenerationLevel;
		internal UInt32 MaxTessellationPatchSize;
		internal UInt32 MaxTessellationControlPerVertexInputComponents;
		internal UInt32 MaxTessellationControlPerVertexOutputComponents;
		internal UInt32 MaxTessellationControlPerPatchOutputComponents;
		internal UInt32 MaxTessellationControlTotalOutputComponents;
		internal UInt32 MaxTessellationEvaluationInputComponents;
		internal UInt32 MaxTessellationEvaluationOutputComponents;
		internal UInt32 MaxGeometryShaderInvocations;
		internal UInt32 MaxGeometryInputComponents;
		internal UInt32 MaxGeometryOutputComponents;
		internal UInt32 MaxGeometryOutputVertices;
		internal UInt32 MaxGeometryTotalOutputComponents;
		internal UInt32 MaxFragmentInputComponents;
		internal UInt32 MaxFragmentOutputAttachments;
		internal UInt32 MaxFragmentDualSrcAttachments;
		internal UInt32 MaxFragmentCombinedOutputResources;
		internal UInt32 MaxComputeSharedMemorySize;
		internal unsafe fixed UInt32 MaxComputeWorkGroupCount[3];
		internal UInt32 MaxComputeWorkGroupInvocations;
		internal unsafe fixed UInt32 MaxComputeWorkGroupSize[3];
		internal UInt32 SubPixelPrecisionBits;
		internal UInt32 SubTexelPrecisionBits;
		internal UInt32 MipmapPrecisionBits;
		internal UInt32 MaxDrawIndexedIndexValue;
		internal UInt32 MaxDrawIndirectCount;
		internal float MaxSamplerLodBias;
		internal float MaxSamplerAnisotropy;
		internal UInt32 MaxViewports;
		internal unsafe fixed UInt32 MaxViewportDimensions[2];
		internal unsafe fixed float ViewportBoundsRange[2];
		internal UInt32 ViewportSubPixelBits;
		internal UIntPtr MinMemoryMapAlignment;
		internal DeviceSize MinTexelBufferOffsetAlignment;
		internal DeviceSize MinUniformBufferOffsetAlignment;
		internal DeviceSize MinStorageBufferOffsetAlignment;
		internal Int32 MinTexelOffset;
		internal UInt32 MaxTexelOffset;
		internal Int32 MinTexelGatherOffset;
		internal UInt32 MaxTexelGatherOffset;
		internal float MinInterpolationOffset;
		internal float MaxInterpolationOffset;
		internal UInt32 SubPixelInterpolationOffsetBits;
		internal UInt32 MaxFramebufferWidth;
		internal UInt32 MaxFramebufferHeight;
		internal UInt32 MaxFramebufferLayers;
		internal SampleCountFlags FramebufferColorSampleCounts;
		internal SampleCountFlags FramebufferDepthSampleCounts;
		internal SampleCountFlags FramebufferStencilSampleCounts;
		internal SampleCountFlags FramebufferNoAttachmentsSampleCounts;
		internal UInt32 MaxColorAttachments;
		internal SampleCountFlags SampledImageColorSampleCounts;
		internal SampleCountFlags SampledImageIntegerSampleCounts;
		internal SampleCountFlags SampledImageDepthSampleCounts;
		internal SampleCountFlags SampledImageStencilSampleCounts;
		internal SampleCountFlags StorageImageSampleCounts;
		internal UInt32 MaxSampleMaskWords;
		internal Bool32 TimestampComputeAndGraphics;
		internal float TimestampPeriod;
		internal UInt32 MaxClipDistances;
		internal UInt32 MaxCullDistances;
		internal UInt32 MaxCombinedClipAndCullDistances;
		internal UInt32 DiscreteQueuePriorities;
		internal unsafe fixed float PointSizeRange[2];
		internal unsafe fixed float LineWidthRange[2];
		internal float PointSizeGranularity;
		internal float LineWidthGranularity;
		internal Bool32 StrictLines;
		internal Bool32 StandardSampleLocations;
		internal DeviceSize OptimalBufferCopyOffsetAlignment;
		internal DeviceSize OptimalBufferCopyRowPitchAlignment;
		internal DeviceSize NonCoherentAtomSize;
	}

	internal partial struct SemaphoreCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
	}

	internal partial struct QueryPoolCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal QueryType QueryType;
		internal UInt32 QueryCount;
		internal QueryPipelineStatisticFlags PipelineStatistics;
	}

	internal partial struct FramebufferCreateInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal UInt64 RenderPass;
		internal UInt32 AttachmentCount;
		internal IntPtr Attachments;
		internal UInt32 Width;
		internal UInt32 Height;
		internal UInt32 Layers;
	}

	internal partial struct SubmitInfo
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 WaitSemaphoreCount;
		internal IntPtr WaitSemaphores;
		internal IntPtr WaitDstStageMask;
		internal UInt32 CommandBufferCount;
		internal IntPtr CommandBuffers;
		internal UInt32 SignalSemaphoreCount;
		internal IntPtr SignalSemaphores;
	}

	internal partial struct DisplayPropertiesKhr
	{
		internal UInt64 Display;
		internal IntPtr DisplayName;
		internal Extent2D PhysicalDimensions;
		internal Extent2D PhysicalResolution;
		internal SurfaceTransformFlagsKhr SupportedTransforms;
		internal Bool32 PlaneReorderPossible;
		internal Bool32 PersistentContent;
	}

	internal partial struct DisplayPlanePropertiesKhr
	{
		internal UInt64 CurrentDisplay;
		internal UInt32 CurrentStackIndex;
	}

	internal partial struct DisplayModePropertiesKhr
	{
		internal UInt64 DisplayMode;
		internal DisplayModeParametersKhr Parameters;
	}

	internal partial struct DisplayModeCreateInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal DisplayModeParametersKhr Parameters;
	}

	internal partial struct DisplaySurfaceCreateInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal UInt64 DisplayMode;
		internal UInt32 PlaneIndex;
		internal UInt32 PlaneStackIndex;
		internal SurfaceTransformFlagsKhr Transform;
		internal float GlobalAlpha;
		internal DisplayPlaneAlphaFlagsKhr AlphaMode;
		internal Extent2D ImageExtent;
	}

	internal partial struct DisplayPresentInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal Rect2D SrcRect;
		internal Rect2D DstRect;
		internal Bool32 Persistent;
	}

	internal partial struct ViSurfaceCreateInfoNn
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal IntPtr Window;
	}

	internal partial struct SwapchainCreateInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal SwapchainCreateFlagsKhr Flags;
		internal UInt64 Surface;
		internal UInt32 MinImageCount;
		internal Format ImageFormat;
		internal ColorSpaceKhr ImageColorSpace;
		internal Extent2D ImageExtent;
		internal UInt32 ImageArrayLayers;
		internal ImageUsageFlags ImageUsage;
		internal SharingMode ImageSharingMode;
		internal UInt32 QueueFamilyIndexCount;
		internal IntPtr QueueFamilyIndices;
		internal SurfaceTransformFlagsKhr PreTransform;
		internal CompositeAlphaFlagsKhr CompositeAlpha;
		internal PresentModeKhr PresentMode;
		internal Bool32 Clipped;
		internal UInt64 OldSwapchain;
	}

	internal partial struct PresentInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 WaitSemaphoreCount;
		internal IntPtr WaitSemaphores;
		internal UInt32 SwapchainCount;
		internal IntPtr Swapchains;
		internal IntPtr ImageIndices;
		internal IntPtr Results;
	}

	internal partial struct DebugReportCallbackCreateInfoExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal DebugReportFlagsExt Flags;
		internal IntPtr PfnCallback;
		internal IntPtr UserData;
	}

	internal partial struct ValidationFlagsExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 DisabledValidationCheckCount;
		internal IntPtr DisabledValidationChecks;
	}

	internal partial struct PipelineRasterizationStateRasterizationOrderAmd
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal RasterizationOrderAmd RasterizationOrder;
	}

	internal partial struct DebugMarkerObjectNameInfoExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal DebugReportObjectTypeExt ObjectType;
		internal UInt64 Object;
		internal IntPtr ObjectName;
	}

	internal partial struct DebugMarkerObjectTagInfoExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal DebugReportObjectTypeExt ObjectType;
		internal UInt64 Object;
		internal UInt64 TagName;
		internal UIntPtr TagSize;
		internal IntPtr Tag;
	}

	internal partial struct DebugMarkerMarkerInfoExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal IntPtr MarkerName;
		internal unsafe fixed float Color[4];
	}

	internal partial struct DedicatedAllocationImageCreateInfoNv
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal Bool32 DedicatedAllocation;
	}

	internal partial struct DedicatedAllocationBufferCreateInfoNv
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal Bool32 DedicatedAllocation;
	}

	internal partial struct DedicatedAllocationMemoryAllocateInfoNv
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 Image;
		internal UInt64 Buffer;
	}

	internal partial struct ExternalMemoryImageCreateInfoNv
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal ExternalMemoryHandleTypeFlagsNv HandleTypes;
	}

	internal partial struct ExportMemoryAllocateInfoNv
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal ExternalMemoryHandleTypeFlagsNv HandleTypes;
	}

	internal partial struct DeviceGeneratedCommandsFeaturesNvx
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal Bool32 ComputeBindingPointSupport;
	}

	internal partial struct DeviceGeneratedCommandsLimitsNvx
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 MaxIndirectCommandsLayoutTokenCount;
		internal UInt32 MaxObjectEntryCounts;
		internal UInt32 MinSequenceCountBufferOffsetAlignment;
		internal UInt32 MinSequenceIndexBufferOffsetAlignment;
		internal UInt32 MinCommandsTokenBufferOffsetAlignment;
	}

	internal partial struct IndirectCommandsTokenNvx
	{
		internal IndirectCommandsTokenTypeNvx TokenType;
		internal UInt64 Buffer;
		internal DeviceSize Offset;
	}

	internal partial struct IndirectCommandsLayoutCreateInfoNvx
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal PipelineBindPoint PipelineBindPoint;
		internal IndirectCommandsLayoutUsageFlagsNvx Flags;
		internal UInt32 TokenCount;
		internal IntPtr Tokens;
	}

	internal partial struct CmdProcessCommandsInfoNvx
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 ObjectTable;
		internal UInt64 IndirectCommandsLayout;
		internal UInt32 IndirectCommandsTokenCount;
		internal IntPtr IndirectCommandsTokens;
		internal UInt32 MaxSequencesCount;
		internal IntPtr TargetCommandBuffer;
		internal UInt64 SequencesCountBuffer;
		internal DeviceSize SequencesCountOffset;
		internal UInt64 SequencesIndexBuffer;
		internal DeviceSize SequencesIndexOffset;
	}

	internal partial struct CmdReserveSpaceForCommandsInfoNvx
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 ObjectTable;
		internal UInt64 IndirectCommandsLayout;
		internal UInt32 MaxSequencesCount;
	}

	internal partial struct ObjectTableCreateInfoNvx
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 ObjectCount;
		internal IntPtr ObjectEntryTypes;
		internal IntPtr ObjectEntryCounts;
		internal IntPtr ObjectEntryUsageFlags;
		internal UInt32 MaxUniformBuffersPerDescriptor;
		internal UInt32 MaxStorageBuffersPerDescriptor;
		internal UInt32 MaxStorageImagesPerDescriptor;
		internal UInt32 MaxSampledImagesPerDescriptor;
		internal UInt32 MaxPipelineLayouts;
	}

	internal partial struct ObjectTablePipelineEntryNvx
	{
		internal ObjectEntryTypeNvx Type;
		internal ObjectEntryUsageFlagsNvx Flags;
		internal UInt64 Pipeline;
	}

	internal partial struct ObjectTableDescriptorSetEntryNvx
	{
		internal ObjectEntryTypeNvx Type;
		internal ObjectEntryUsageFlagsNvx Flags;
		internal UInt64 PipelineLayout;
		internal UInt64 DescriptorSet;
	}

	internal partial struct ObjectTableVertexBufferEntryNvx
	{
		internal ObjectEntryTypeNvx Type;
		internal ObjectEntryUsageFlagsNvx Flags;
		internal UInt64 Buffer;
	}

	internal partial struct ObjectTableIndexBufferEntryNvx
	{
		internal ObjectEntryTypeNvx Type;
		internal ObjectEntryUsageFlagsNvx Flags;
		internal UInt64 Buffer;
		internal IndexType IndexType;
	}

	internal partial struct ObjectTablePushConstantEntryNvx
	{
		internal ObjectEntryTypeNvx Type;
		internal ObjectEntryUsageFlagsNvx Flags;
		internal UInt64 PipelineLayout;
		internal ShaderStageFlags StageFlags;
	}

	internal partial struct PhysicalDeviceFeatures2Khr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal PhysicalDeviceFeatures Features;
	}

	internal partial struct PhysicalDeviceProperties2Khr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal PhysicalDeviceProperties Properties;
	}

	internal partial struct FormatProperties2Khr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal FormatProperties FormatProperties;
	}

	internal partial struct ImageFormatProperties2Khr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal ImageFormatProperties ImageFormatProperties;
	}

	internal partial struct PhysicalDeviceImageFormatInfo2Khr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal Format Format;
		internal ImageType Type;
		internal ImageTiling Tiling;
		internal ImageUsageFlags Usage;
		internal ImageCreateFlags Flags;
	}

	internal partial struct QueueFamilyProperties2Khr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal QueueFamilyProperties QueueFamilyProperties;
	}

	internal partial struct PhysicalDeviceMemoryProperties2Khr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal PhysicalDeviceMemoryProperties MemoryProperties;
	}

	internal partial struct SparseImageFormatProperties2Khr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal SparseImageFormatProperties Properties;
	}

	internal partial struct PhysicalDeviceSparseImageFormatInfo2Khr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal Format Format;
		internal ImageType Type;
		internal SampleCountFlags Samples;
		internal ImageUsageFlags Usage;
		internal ImageTiling Tiling;
	}

	internal partial struct PhysicalDevicePushDescriptorPropertiesKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 MaxPushDescriptors;
	}

	internal partial struct PresentRegionsKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 SwapchainCount;
		internal IntPtr Regions;
	}

	internal partial struct PresentRegionKhr
	{
		internal UInt32 RectangleCount;
		internal IntPtr Rectangles;
	}

	internal partial struct PhysicalDeviceVariablePointerFeaturesKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal Bool32 VariablePointersStorageBuffer;
		internal Bool32 VariablePointers;
	}

	internal partial struct PhysicalDeviceExternalImageFormatInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal ExternalMemoryHandleTypeFlagsKhr HandleType;
	}

	internal partial struct ExternalImageFormatPropertiesKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal ExternalMemoryPropertiesKhr ExternalMemoryProperties;
	}

	internal partial struct PhysicalDeviceExternalBufferInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal BufferCreateFlags Flags;
		internal BufferUsageFlags Usage;
		internal ExternalMemoryHandleTypeFlagsKhr HandleType;
	}

	internal partial struct ExternalBufferPropertiesKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal ExternalMemoryPropertiesKhr ExternalMemoryProperties;
	}

	internal partial struct PhysicalDeviceIDPropertiesKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal unsafe fixed byte DeviceUuid[16];
		internal unsafe fixed byte DriverUuid[16];
		internal unsafe fixed byte DeviceLuid[8];
		internal UInt32 DeviceNodeMask;
		internal Bool32 DeviceLuidvalid;
	}

	internal partial struct ExternalMemoryImageCreateInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal ExternalMemoryHandleTypeFlagsKhr HandleTypes;
	}

	internal partial struct ExternalMemoryBufferCreateInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal ExternalMemoryHandleTypeFlagsKhr HandleTypes;
	}

	internal partial struct ExportMemoryAllocateInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal ExternalMemoryHandleTypeFlagsKhr HandleTypes;
	}

	internal partial struct MemoryWin32HandlePropertiesKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 MemoryTypeBits;
	}

	internal partial struct MemoryGetWin32HandleInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 Memory;
		internal ExternalMemoryHandleTypeFlagsKhr HandleType;
	}

	internal partial struct ImportMemoryFdInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal ExternalMemoryHandleTypeFlagsKhr HandleType;
		internal int Fd;
	}

	internal partial struct MemoryFdPropertiesKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 MemoryTypeBits;
	}

	internal partial struct MemoryGetFdInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 Memory;
		internal ExternalMemoryHandleTypeFlagsKhr HandleType;
	}

	internal partial struct Win32KeyedMutexAcquireReleaseInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 AcquireCount;
		internal IntPtr AcquireSyncs;
		internal IntPtr AcquireKeys;
		internal IntPtr AcquireTimeouts;
		internal UInt32 ReleaseCount;
		internal IntPtr ReleaseSyncs;
		internal IntPtr ReleaseKeys;
	}

	internal partial struct PhysicalDeviceExternalSemaphoreInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal ExternalSemaphoreHandleTypeFlagsKhr HandleType;
	}

	internal partial struct ExternalSemaphorePropertiesKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal ExternalSemaphoreHandleTypeFlagsKhr ExportFromImportedHandleTypes;
		internal ExternalSemaphoreHandleTypeFlagsKhr CompatibleHandleTypes;
		internal ExternalSemaphoreFeatureFlagsKhr ExternalSemaphoreFeatures;
	}

	internal partial struct ExportSemaphoreCreateInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal ExternalSemaphoreHandleTypeFlagsKhr HandleTypes;
	}

	internal partial struct D3D12FenceSubmitInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 WaitSemaphoreValuesCount;
		internal IntPtr WaitSemaphoreValues;
		internal UInt32 SignalSemaphoreValuesCount;
		internal IntPtr SignalSemaphoreValues;
	}

	internal partial struct SemaphoreGetWin32HandleInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 Semaphore;
		internal ExternalSemaphoreHandleTypeFlagsKhr HandleType;
	}

	internal partial struct ImportSemaphoreFdInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 Semaphore;
		internal SemaphoreImportFlagsKhr Flags;
		internal ExternalSemaphoreHandleTypeFlagsKhr HandleType;
		internal int Fd;
	}

	internal partial struct SemaphoreGetFdInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 Semaphore;
		internal ExternalSemaphoreHandleTypeFlagsKhr HandleType;
	}

	internal partial struct PhysicalDeviceExternalFenceInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal ExternalFenceHandleTypeFlagsKhr HandleType;
	}

	internal partial struct ExternalFencePropertiesKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal ExternalFenceHandleTypeFlagsKhr ExportFromImportedHandleTypes;
		internal ExternalFenceHandleTypeFlagsKhr CompatibleHandleTypes;
		internal ExternalFenceFeatureFlagsKhr ExternalFenceFeatures;
	}

	internal partial struct ExportFenceCreateInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal ExternalFenceHandleTypeFlagsKhr HandleTypes;
	}

	internal partial struct FenceGetWin32HandleInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 Fence;
		internal ExternalFenceHandleTypeFlagsKhr HandleType;
	}

	internal partial struct ImportFenceFdInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 Fence;
		internal FenceImportFlagsKhr Flags;
		internal ExternalFenceHandleTypeFlagsKhr HandleType;
		internal int Fd;
	}

	internal partial struct FenceGetFdInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 Fence;
		internal ExternalFenceHandleTypeFlagsKhr HandleType;
	}

	internal partial struct PhysicalDeviceMultiviewFeaturesKhx
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal Bool32 Multiview;
		internal Bool32 MultiviewGeometryShader;
		internal Bool32 MultiviewTessellationShader;
	}

	internal partial struct PhysicalDeviceMultiviewPropertiesKhx
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 MaxMultiviewViewCount;
		internal UInt32 MaxMultiviewInstanceIndex;
	}

	internal partial struct RenderPassMultiviewCreateInfoKhx
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 SubpassCount;
		internal IntPtr ViewMasks;
		internal UInt32 DependencyCount;
		internal IntPtr ViewOffsets;
		internal UInt32 CorrelationMaskCount;
		internal IntPtr CorrelationMasks;
	}

	internal partial struct SurfaceCapabilities2Ext
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 MinImageCount;
		internal UInt32 MaxImageCount;
		internal Extent2D CurrentExtent;
		internal Extent2D MinImageExtent;
		internal Extent2D MaxImageExtent;
		internal UInt32 MaxImageArrayLayers;
		internal SurfaceTransformFlagsKhr SupportedTransforms;
		internal SurfaceTransformFlagsKhr CurrentTransform;
		internal CompositeAlphaFlagsKhr SupportedCompositeAlpha;
		internal ImageUsageFlags SupportedUsageFlags;
		internal SurfaceCounterFlagsExt SupportedSurfaceCounters;
	}

	internal partial struct DisplayPowerInfoExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal DisplayPowerStateExt PowerState;
	}

	internal partial struct DeviceEventInfoExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal DeviceEventTypeExt DeviceEvent;
	}

	internal partial struct DisplayEventInfoExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal DisplayEventTypeExt DisplayEvent;
	}

	internal partial struct SwapchainCounterCreateInfoExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal SurfaceCounterFlagsExt SurfaceCounters;
	}

	internal partial struct MemoryAllocateFlagsInfoKhx
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal MemoryAllocateFlagsKhx Flags;
		internal UInt32 DeviceMask;
	}

	internal partial struct BindBufferMemoryInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 Buffer;
		internal UInt64 Memory;
		internal DeviceSize MemoryOffset;
	}

	internal partial struct BindBufferMemoryDeviceGroupInfoKhx
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 DeviceIndexCount;
		internal IntPtr DeviceIndices;
	}

	internal partial struct BindImageMemoryInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 Image;
		internal UInt64 Memory;
		internal DeviceSize MemoryOffset;
	}

	internal partial struct BindImageMemoryDeviceGroupInfoKhx
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 DeviceIndexCount;
		internal IntPtr DeviceIndices;
		internal UInt32 SfrrectCount;
		internal IntPtr Sfrrects;
	}

	internal partial struct DeviceGroupRenderPassBeginInfoKhx
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 DeviceMask;
		internal UInt32 DeviceRenderAreaCount;
		internal IntPtr DeviceRenderAreas;
	}

	internal partial struct DeviceGroupCommandBufferBeginInfoKhx
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 DeviceMask;
	}

	internal partial struct DeviceGroupSubmitInfoKhx
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 WaitSemaphoreCount;
		internal IntPtr WaitSemaphoreDeviceIndices;
		internal UInt32 CommandBufferCount;
		internal IntPtr CommandBufferDeviceMasks;
		internal UInt32 SignalSemaphoreCount;
		internal IntPtr SignalSemaphoreDeviceIndices;
	}

	internal partial struct DeviceGroupBindSparseInfoKhx
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 ResourceDeviceIndex;
		internal UInt32 MemoryDeviceIndex;
	}

	internal partial struct DeviceGroupPresentCapabilitiesKhx
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal unsafe fixed UInt32 PresentMask[32];
		internal DeviceGroupPresentModeFlagsKhx Modes;
	}

	internal partial struct ImageSwapchainCreateInfoKhx
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 Swapchain;
	}

	internal partial struct BindImageMemorySwapchainInfoKhx
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 Swapchain;
		internal UInt32 ImageIndex;
	}

	internal partial struct AcquireNextImageInfoKhx
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 Swapchain;
		internal UInt64 Timeout;
		internal UInt64 Semaphore;
		internal UInt64 Fence;
		internal UInt32 DeviceMask;
	}

	internal partial struct DeviceGroupPresentInfoKhx
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 SwapchainCount;
		internal IntPtr DeviceMasks;
		internal DeviceGroupPresentModeFlagsKhx Mode;
	}

	internal partial struct DeviceGroupDeviceCreateInfoKhx
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 PhysicalDeviceCount;
		internal IntPtr PhysicalDevices;
	}

	internal partial struct DeviceGroupSwapchainCreateInfoKhx
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal DeviceGroupPresentModeFlagsKhx Modes;
	}

	internal partial struct DescriptorUpdateTemplateCreateInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal UInt32 DescriptorUpdateEntryCount;
		internal IntPtr DescriptorUpdateEntries;
		internal DescriptorUpdateTemplateTypeKhr TemplateType;
		internal UInt64 DescriptorSetLayout;
		internal PipelineBindPoint PipelineBindPoint;
		internal UInt64 PipelineLayout;
		internal UInt32 Set;
	}

	internal partial struct HdrMetadataExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal XYColorExt DisplayPrimaryRed;
		internal XYColorExt DisplayPrimaryGreen;
		internal XYColorExt DisplayPrimaryBlue;
		internal XYColorExt WhitePoint;
		internal float MaxLuminance;
		internal float MinLuminance;
		internal float MaxContentLightLevel;
		internal float MaxFrameAverageLightLevel;
	}

	internal partial struct PresentTimesInfoGoogle
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 SwapchainCount;
		internal IntPtr Times;
	}

	internal partial struct IOSSurfaceCreateInfoMvk
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal IntPtr View;
	}

	internal partial struct MacOSSurfaceCreateInfoMvk
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal IntPtr View;
	}

	internal partial struct PipelineViewportWScalingStateCreateInfoNv
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal Bool32 ViewportWscalingEnable;
		internal UInt32 ViewportCount;
		internal IntPtr ViewportWscalings;
	}

	internal partial struct PipelineViewportSwizzleStateCreateInfoNv
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal UInt32 ViewportCount;
		internal IntPtr ViewportSwizzles;
	}

	internal partial struct PhysicalDeviceDiscardRectanglePropertiesExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 MaxDiscardRectangles;
	}

	internal partial struct PipelineDiscardRectangleStateCreateInfoExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal DiscardRectangleModeExt DiscardRectangleMode;
		internal UInt32 DiscardRectangleCount;
		internal IntPtr DiscardRectangles;
	}

	internal partial struct PhysicalDeviceMultiviewPerViewAttributesPropertiesNvx
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal Bool32 PerViewPositionAllComponents;
	}

	internal partial struct RenderPassInputAttachmentAspectCreateInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 AspectReferenceCount;
		internal IntPtr AspectReferences;
	}

	internal partial struct PhysicalDeviceSurfaceInfo2Khr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 Surface;
	}

	internal partial struct SurfaceCapabilities2Khr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal SurfaceCapabilitiesKhr SurfaceCapabilities;
	}

	internal partial struct SurfaceFormat2Khr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal SurfaceFormatKhr SurfaceFormat;
	}

	internal partial struct SharedPresentSurfaceCapabilitiesKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal ImageUsageFlags SharedPresentSupportedUsageFlags;
	}

	internal partial struct PhysicalDevice16BitStorageFeaturesKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal Bool32 StorageBuffer16BitAccess;
		internal Bool32 UniformAndStorageBuffer16BitAccess;
		internal Bool32 StoragePushConstant16;
		internal Bool32 StorageInputOutput16;
	}

	internal partial struct BufferMemoryRequirementsInfo2Khr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 Buffer;
	}

	internal partial struct ImageMemoryRequirementsInfo2Khr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 Image;
	}

	internal partial struct ImageSparseMemoryRequirementsInfo2Khr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 Image;
	}

	internal partial struct MemoryRequirements2Khr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal MemoryRequirements MemoryRequirements;
	}

	internal partial struct SparseImageMemoryRequirements2Khr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal SparseImageMemoryRequirements MemoryRequirements;
	}

	internal partial struct PhysicalDevicePointClippingPropertiesKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal PointClippingBehaviorKhr PointClippingBehavior;
	}

	internal partial struct MemoryDedicatedRequirementsKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal Bool32 PrefersDedicatedAllocation;
		internal Bool32 RequiresDedicatedAllocation;
	}

	internal partial struct MemoryDedicatedAllocateInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 Image;
		internal UInt64 Buffer;
	}

	internal partial struct ImageViewUsageCreateInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal ImageUsageFlags Usage;
	}

	internal partial struct PipelineTessellationDomainOriginStateCreateInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal TessellationDomainOriginKhr DomainOrigin;
	}

	internal partial struct SamplerYcbcrConversionInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 Conversion;
	}

	internal partial struct SamplerYcbcrConversionCreateInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal Format Format;
		internal SamplerYcbcrModelConversionKhr YcbcrModel;
		internal SamplerYcbcrRangeKhr YcbcrRange;
		internal ComponentMapping Components;
		internal ChromaLocationKhr XChromaOffset;
		internal ChromaLocationKhr YChromaOffset;
		internal Filter ChromaFilter;
		internal Bool32 ForceExplicitReconstruction;
	}

	internal partial struct BindImagePlaneMemoryInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal ImageAspectFlags PlaneAspect;
	}

	internal partial struct ImagePlaneMemoryRequirementsInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal ImageAspectFlags PlaneAspect;
	}

	internal partial struct PhysicalDeviceSamplerYcbcrConversionFeaturesKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal Bool32 SamplerYcbcrConversion;
	}

	internal partial struct SamplerYcbcrConversionImageFormatPropertiesKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 CombinedImageSamplerDescriptorCount;
	}

	internal partial struct TextureLODGatherFormatPropertiesAmd
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal Bool32 SupportsTextureGatherLodbiasAmd;
	}

	internal partial struct PipelineCoverageToColorStateCreateInfoNv
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal Bool32 CoverageToColorEnable;
		internal UInt32 CoverageToColorLocation;
	}

	internal partial struct PhysicalDeviceSamplerFilterMinmaxPropertiesExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal Bool32 FilterMinmaxSingleComponentFormats;
		internal Bool32 FilterMinmaxImageComponentMapping;
	}

	internal partial struct SampleLocationsInfoExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal SampleCountFlags SampleLocationsPerPixel;
		internal Extent2D SampleLocationGridSize;
		internal UInt32 SampleLocationsCount;
		internal IntPtr SampleLocations;
	}

	internal partial struct AttachmentSampleLocationsExt
	{
		internal UInt32 AttachmentIndex;
		internal SampleLocationsInfoExt SampleLocationsInfo;
	}

	internal partial struct SubpassSampleLocationsExt
	{
		internal UInt32 SubpassIndex;
		internal SampleLocationsInfoExt SampleLocationsInfo;
	}

	internal partial struct RenderPassSampleLocationsBeginInfoExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 AttachmentInitialSampleLocationsCount;
		internal IntPtr AttachmentInitialSampleLocations;
		internal UInt32 PostSubpassSampleLocationsCount;
		internal IntPtr PostSubpassSampleLocations;
	}

	internal partial struct PipelineSampleLocationsStateCreateInfoExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal Bool32 SampleLocationsEnable;
		internal SampleLocationsInfoExt SampleLocationsInfo;
	}

	internal partial struct PhysicalDeviceSampleLocationsPropertiesExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal SampleCountFlags SampleLocationSampleCounts;
		internal Extent2D MaxSampleLocationGridSize;
		internal unsafe fixed float SampleLocationCoordinateRange[2];
		internal UInt32 SampleLocationSubPixelBits;
		internal Bool32 VariableSampleLocations;
	}

	internal partial struct MultisamplePropertiesExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal Extent2D MaxSampleLocationGridSize;
	}

	internal partial struct SamplerReductionModeCreateInfoExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal SamplerReductionModeExt ReductionMode;
	}

	internal partial struct PhysicalDeviceBlendOperationAdvancedFeaturesExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal Bool32 AdvancedBlendCoherentOperations;
	}

	internal partial struct PhysicalDeviceBlendOperationAdvancedPropertiesExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 AdvancedBlendMaxColorAttachments;
		internal Bool32 AdvancedBlendIndependentBlend;
		internal Bool32 AdvancedBlendNonPremultipliedSrcColor;
		internal Bool32 AdvancedBlendNonPremultipliedDstColor;
		internal Bool32 AdvancedBlendCorrelatedOverlap;
		internal Bool32 AdvancedBlendAllOperations;
	}

	internal partial struct PipelineColorBlendAdvancedStateCreateInfoExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal Bool32 SrcPremultiplied;
		internal Bool32 DstPremultiplied;
		internal BlendOverlapExt BlendOverlap;
	}

	internal partial struct PipelineCoverageModulationStateCreateInfoNv
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal CoverageModulationModeNv CoverageModulationMode;
		internal Bool32 CoverageModulationTableEnable;
		internal UInt32 CoverageModulationTableCount;
		internal IntPtr CoverageModulationTable;
	}

	internal partial struct ImageFormatListCreateInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 ViewFormatCount;
		internal IntPtr ViewFormats;
	}

	internal partial struct ValidationCacheCreateInfoExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal UIntPtr InitialDataSize;
		internal IntPtr InitialData;
	}

	internal partial struct ShaderModuleValidationCacheCreateInfoExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt64 ValidationCache;
	}

	internal partial struct ShaderStatisticsInfoAmd
	{
		internal ShaderStageFlags ShaderStageMask;
		internal ShaderResourceUsageAmd ResourceUsage;
		internal UInt32 NumPhysicalVgprs;
		internal UInt32 NumPhysicalSgprs;
		internal UInt32 NumAvailableVgprs;
		internal UInt32 NumAvailableSgprs;
		internal unsafe fixed UInt32 ComputeWorkGroupSize[3];
	}

	internal partial struct DeviceQueueGlobalPriorityCreateInfoExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal QueueGlobalPriorityExt GlobalPriority;
	}

	internal partial struct ImportMemoryHostPointerInfoExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal ExternalMemoryHandleTypeFlagsKhr HandleType;
		internal IntPtr HostPointer;
	}

	internal partial struct MemoryHostPointerPropertiesExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 MemoryTypeBits;
	}

	internal partial struct PhysicalDeviceExternalMemoryHostPropertiesExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal DeviceSize MinImportedHostPointerAlignment;
	}

	internal partial struct PhysicalDeviceConservativeRasterizationPropertiesExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal float PrimitiveOverestimationSize;
		internal float MaxExtraPrimitiveOverestimationSize;
		internal float ExtraPrimitiveOverestimationSizeGranularity;
		internal Bool32 PrimitiveUnderestimation;
		internal Bool32 ConservativePointAndLineRasterization;
		internal Bool32 DegenerateTrianglesRasterized;
		internal Bool32 DegenerateLinesRasterized;
		internal Bool32 FullyCoveredFragmentShaderInputVariable;
		internal Bool32 ConservativeRasterizationPostDepthCoverage;
	}

	internal partial struct PipelineRasterizationConservativeStateCreateInfoExt
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal ConservativeRasterizationModeExt ConservativeRasterizationMode;
		internal float ExtraPrimitiveOverestimationSize;
	}
}
