/* Please note that this file is generated by the VulkanSharp's generator. Do not edit directly.

   Licensed under the MIT license.

   Copyright 2016 Xamarin Inc

   This notice may not be removed from any source distribution.
   See LICENSE file for licensing details.
*/

using System;
using System.Runtime.InteropServices;

namespace Vulkan.Interop
{
	[StructLayout (LayoutKind.Explicit)]
	internal partial struct ClearColorValue
	{
		[FieldOffset (0)] internal unsafe fixed float Float32[4];
		[FieldOffset (0)] internal unsafe fixed Int32 Int32[4];
		[FieldOffset (0)] internal unsafe fixed UInt32 Uint32[4];
	}

	[StructLayout (LayoutKind.Explicit)]
	internal partial struct ClearValue
	{
		[FieldOffset (0)] internal ClearColorValue Color;
		[FieldOffset (0)] internal ClearDepthStencilValue DepthStencil;
	}
}
