/* Please note that this file is generated by the VulkanSharp's generator. Do not edit directly.

   Licensed under the MIT license.

   Copyright 2016 Xamarin Inc

   This notice may not be removed from any source distribution.
   See LICENSE file for licensing details.
*/

using System;
using System.Runtime.InteropServices;

namespace Vulkan.Interop
{
	[StructLayout (LayoutKind.Explicit)]
	internal struct ClearColorValue
	{
		[FieldOffset (0)] internal float Float32;
		[FieldOffset (0)] internal Int32 Int32;
		[FieldOffset (0)] internal UInt32 Uint32;
	}

	[StructLayout (LayoutKind.Explicit)]
	internal struct ClearValue
	{
		[FieldOffset (0)] internal IntPtr Color;
		[FieldOffset (0)] internal IntPtr DepthStencil;
	}
}
