/* Please note that this file is generated by the VulkanSharp's generator. Do not edit directly.

   Licensed under the MIT license.

   Copyright 2016 Xamarin Inc

   This notice may not be removed from any source distribution.
   See LICENSE file for licensing details.
*/

using System;
using System.Runtime.InteropServices;

namespace Vulkan
{
	unsafe public class AndroidSurfaceCreateInfoKhr
	{
		internal Android.Interop.AndroidSurfaceCreateInfoKhr* m;

		public AndroidSurfaceCreateInfoKhr ()
		{
			m = (Android.Interop.AndroidSurfaceCreateInfoKhr*) Interop.Structure.Allocate (typeof (Android.Interop.AndroidSurfaceCreateInfoKhr));
			m->SType = StructureType.AndroidSurfaceCreateInfoKhr;
		}

		public UInt32 Flags {
			get { return m->Flags; }
			set { m->Flags = value; }
		}

		public IntPtr Window {
			get { return m->Window; }
			set { m->Window = value; }
		}
	}

}
