/* Please note that this file is generated by the VulkanSharp's generator. Do not edit directly.

   Licensed under the MIT license.

   Copyright 2016 Xamarin Inc

   This notice may not be removed from any source distribution.
   See LICENSE file for licensing details.
*/

using System;
using System.Runtime.InteropServices;

namespace Vulkan.Android
{
	unsafe public partial class AndroidSurfaceCreateInfoKhr : MarshalledObject
	{
		public UInt32 Flags {
			get { return m->Flags; }
			set { m->Flags = value; }
		}

		public IntPtr Window {
			get { return m->Window; }
			set { m->Window = value; }
		}
		internal Android.Interop.AndroidSurfaceCreateInfoKhr* m {

			get {
				return (Android.Interop.AndroidSurfaceCreateInfoKhr*)native.Handle;
			}
		}

		public AndroidSurfaceCreateInfoKhr ()
		{
			native = Vulkan.Interop.Structure.Allocate (typeof (Android.Interop.AndroidSurfaceCreateInfoKhr));
			Initialize ();
		}

		internal AndroidSurfaceCreateInfoKhr (NativePointer pointer)
		{
			native = pointer;
			Initialize ();
		}


		internal void Initialize ()
		{
			m->SType = StructureType.AndroidSurfaceCreateInfoKhr;
		}

	}

}
