/* Please note that this file is generated by the VulkanSharp's generator. Do not edit directly.

   Licensed under the MIT license.

   Copyright 2016 Xamarin Inc

   This notice may not be removed from any source distribution.
   See LICENSE file for licensing details.
*/

using System;

namespace Vulkan.Windows.Interop
{
	internal partial struct Win32SurfaceCreateInfoKhr
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 Flags;
		internal IntPtr Hinstance;
		internal IntPtr Hwnd;
	}

	internal partial struct ImportMemoryWin32HandleInfoNv
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal ExternalMemoryHandleTypeFlagsNv HandleType;
		internal IntPtr Handle;
	}

	internal partial struct ExportMemoryWin32HandleInfoNv
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal IntPtr Attributes;
		internal UInt32 DwAccess;
	}

	internal partial struct Win32KeyedMutexAcquireReleaseInfoNv
	{
		internal StructureType SType;
		internal IntPtr Next;
		internal UInt32 AcquireCount;
		internal IntPtr AcquireSyncs;
		internal IntPtr AcquireKeys;
		internal IntPtr AcquireTimeoutMilliseconds;
		internal UInt32 ReleaseCount;
		internal IntPtr ReleaseSyncs;
		internal IntPtr ReleaseKeys;
	}

}
