/* Please note that this file is generated by the VulkanSharp's generator. Do not edit directly.

   Licensed under the MIT license.

   Copyright 2016 Xamarin Inc

   This notice may not be removed from any source distribution.
   See LICENSE file for licensing details.
*/

using System;
using System.Runtime.InteropServices;

namespace Vulkan
{
	unsafe public class ClearColorValue
	{
		internal Interop.ClearColorValue* m;

		public ClearColorValue ()
		{
			m = (Interop.ClearColorValue*) Interop.Structure.Allocate (typeof (Interop.ClearColorValue));
		}

		public float Float32 {
			get { return m->Float32; }
			set { m->Float32 = value; }
		}

		public Int32 Int32 {
			get { return m->Int32; }
			set { m->Int32 = value; }
		}

		public UInt32 Uint32 {
			get { return m->Uint32; }
			set { m->Uint32 = value; }
		}
	}

	[StructLayout (LayoutKind.Explicit)]
	unsafe public struct ClearValue
	{
		[FieldOffset (0)] public IntPtr Color;
		[FieldOffset (0)] public ClearDepthStencilValue DepthStencil;
	}
}
